# Generated by Django 5.1.7 on 2026-04-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='recommended_analysis_types',
            field=models.ManyToManyField(blank=True, related_name='medical_records', to='core.analysistype'),
        ),
    ]
